
# Name of website
title: Dongmin Chun

logo: /assets/img/dd2.bmp

# text below image
#description: Economist / Bank of Korea


#email: "dmchun90[at]gmail[dot]com"


#show_downloads: true
theme: jekyll-theme-minimal

