
# Name of website
title: Dongmin Chun

# Your name to show in the footer
author: Dongmin Chun


email: "dmchun90[at]gmail[dot]com"


subtitle: Economist / Bank of Korea
#logo: /dd/dd.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
